### ISSUE TITLE
Flip doesn't work with videos either

### ISSUE THREAD

**Issue by melarozz** [CV-goes-frr/CVIP#81]
<img width="944" alt="Снимок экрана 2024-06-21 в 14 14 52" src="https://github.com/CV-goes-frr/CVIP/assets/64836918/3feee7b0-a340-49a6-8da1-86c452f7f5b2">
<img width="978" alt="Снимок экрана 2024-06-21 в 14 15 10" src="https://github.com/CV-goes-frr/CVIP/assets/64836918/f18df41a-c0c3-466e-ba70-bd2878b5a820">

None of the options work. Might be problem with .mov, didn't manage to check yet

**Comment by MurenMurenus** [comment]
CVIP tried to flip it as a photo (no -v option in the query)

**Comment by melarozz** [comment]
Issue solved by PR #85
